flowchart TD
    A(Trigger) -->|ListOnDiskBlockIdsCmd| B[Conns]
    A -->|ListOnDiskBlockIdsCmd| C(LocalBlockIdLister)
    B -->|ListOnDiskBlockIdsCmd| C
    C --> |OnDiskBlockIdList| B
    C --> |OnDiskBlockIdList| D(Collector)
    B --> |OnDiskBlockIdList| D
    D --> |BalanceReqId| E[FetchActiveIds]
    E --> |FilesystemBlockIdList| D
    D --> |BalanceReqId| F(DeleteUnused)
    D --> |BalanceReqId| G(FillMissing)
    F --> |DeleteBlockId| I[DisksBlockDelete]
    F --> |DeleteBlockId| B
    B --> |DeleteBlockId| I
