flowchart TD
    A[Ui] -->|AddDiskReq| B(Disks)
    B -->|RemoteAddDiskReq| C[Conns]
    C -->|AddDiskReq| B
    D(DiskLoader) -->|AddDiskReq| B
    B --> |IamDisksUpdate| E(IamSender)
    E -->|Iam| C
    C --> F(IamReceiver)
    F --> |AddDiskReq|B
    B --> |Disk| G[LocalBlockReadResponse]
    B --> |Disk| H[LocalBlockSaveResponse]