flowchart TD
    A[Conns] -->|IamConnId| B(IamReceiver)
    A[Conns] -->|Iam| C[Disks]
    A[Conns] -->|AddDiskReq| C[Disks]
    A[Conns] -->|SaveToDiskReq| D[BlockSaver]
    A[Conns] -->|SaveToDiskResp| D[BlockSaver]
    A[Conns] -->|GetFromDiskReq| E[BlockReader]
    A[Conns] -->|GetFromDiskResp| E[BlockReader]
